services:
  - type: web
    name: spotokn
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
      - key: HEADLESS
        value: true
